# Generated by Django 5.0.7 on 2024-07-23 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=42, unique=True)),
                ('topic', models.TextField(max_length=42)),
                ('question', models.TextField(max_length=420)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='TeamList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamSlug', models.SlugField(unique=True)),
                ('team', models.CharField(max_length=42)),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerSets', models.TextField(max_length=70)),
                ('qID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskMaster.question')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
            },
        ),
        migrations.CreateModel(
            name='RoundList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=42, unique=True)),
                ('RLSlug', models.SlugField(unique=True)),
                ('mark', models.IntegerField(default=0, null=True)),
                ('team_answer', models.CharField(max_length=70, null=True)),
                ('qTitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskMaster.question')),
            ],
            options={
                'verbose_name': 'Сетка ответов',
                'verbose_name_plural': 'Сетки ответов',
            },
        ),
        migrations.CreateModel(
            name='GameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('winner', models.CharField(default='не определён', max_length=42)),
                ('gameNAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskMaster.roundlist')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
