# Generated by Django 5.0.7 on 2024-07-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamlist',
            name='member',
        ),
        migrations.AddField(
            model_name='teamlist',
            name='member',
            field=models.ManyToManyField(to='users.profile'),
        ),
    ]
