# Generated by Django 5.0.7 on 2024-07-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0003_remove_teamlist_member_teamlist_member'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamlist',
            name='member',
            field=models.ManyToManyField(null=True, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='teamlist',
            name='team',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='teamlist',
            name='teamSlug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
