# Generated by Django 5.0.7 on 2024-07-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0004_alter_teamlist_member_alter_teamlist_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamlist',
            name='team',
            field=models.CharField(max_length=42, unique=True),
        ),
    ]
