# Generated by Django 5.0.7 on 2024-07-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0005_alter_teamlist_team'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamlist',
            name='member',
            field=models.ManyToManyField(to='users.profile'),
        ),
    ]
