# Generated by Django 5.0.7 on 2024-08-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0007_roundlist_target_teamlist_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlist',
            name='reserved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
