# Generated by Django 5.0.7 on 2024-08-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0008_teamlist_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundlist',
            name='RLSlug',
        ),
    ]
