# Generated by Django 5.0.7 on 2024-08-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0009_remove_roundlist_rlslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundlist',
            name='gameName',
            field=models.CharField(max_length=42),
        ),
    ]
