# Generated by Django 5.0.7 on 2024-08-05 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0011_alter_gamelist_gamename_alter_roundlist_gamename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundlist',
            name='gameName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskMaster.gamelist', to_field='gameNAME'),
        ),
    ]
