# Generated by Django 5.0.7 on 2024-08-08 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0012_alter_roundlist_gamename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundlist',
            name='qTitle',
        ),
        migrations.RemoveField(
            model_name='roundlist',
            name='target',
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.SmallIntegerField(default=1)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskMaster.gamelist', to_field='gameNAME')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskMaster.teamlist', to_field='team')),
            ],
            options={
                'verbose_name': 'Раунд',
                'verbose_name_plural': 'Раунды',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskMaster.gamelist', to_field='gameNAME')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskMaster.question', to_field='title')),
            ],
            options={
                'verbose_name': 'Раунд',
                'verbose_name_plural': 'Раунды',
            },
        ),
        migrations.AddField(
            model_name='roundlist',
            name='round',
            field=models.ManyToManyField(to='taskMaster.round'),
        ),
    ]
