# Generated by Django 5.0.7 on 2024-08-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0013_remove_roundlist_qtitle_remove_roundlist_target_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamescore',
            options={'verbose_name': 'Счет игры', 'verbose_name_plural': 'Счеты игр'},
        ),
        migrations.AddField(
            model_name='question',
            name='cost',
            field=models.SmallIntegerField(blank=True, default=5, null=True),
        ),
    ]
