# Generated by Django 5.0.7 on 2024-08-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0014_alter_gamescore_options_question_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundlist',
            name='round',
        ),
        migrations.AddField(
            model_name='roundlist',
            name='round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
