# Generated by Django 4.2.15 on 2024-08-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0015_remove_roundlist_round_roundlist_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelist',
            name='RLSlug',
            field=models.SlugField(default=1212, max_length=42, unique=True),
            preserve_default=False,
        ),
    ]
