# Generated by Django 4.2.15 on 2024-08-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskMaster', '0016_gamelist_rlslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='winner',
            field=models.CharField(default='Не определён', max_length=42),
        ),
    ]
